kind: MachineConfig
apiVersion: machineconfiguration.openshift.io/v1
metadata:
  name: 97-worker-gremlin-semodule  # RECOMMEND CHANGE NAME TO MATCH NODE ROLE
  creationTimestamp: 
  labels:
    machineconfiguration.openshift.io/role: worker # CHANGE TO MATCH NODE ROLE
spec:
  osImageURL: ''
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - path: "/etc/selinux/gremlin-ocp4.cil"
        contents:
          source: data:text/plain;charset=utf-8;base64,KGJsb2NrIGdyZW1saW4KICAgIChibG9ja2luaGVyaXQgY29udGFpbmVyKQogICAgKGJsb2NraW5oZXJpdCBuZXRfY29udGFpbmVyKQogICAgKGFsbG93IHByb2Nlc3MgcHJvY190IChsbmtfZmlsZSAocmVhZCkpKQogICAgKGFsbG93IHByb2Nlc3Mga2VybmVsX3QgKHN5c3RlbSAobW9kdWxlX3JlcXVlc3QpKSkKICAgIChhbGxvdyBwcm9jZXNzIGNvbnRhaW5lcl9sb2dfdCAoIGRpciAoIG9wZW4gcmVhZCBnZXRhdHRyIGxvY2sgc2VhcmNoIGlvY3RsIGFkZF9uYW1lIHJlbW92ZV9uYW1lIHdyaXRlIGNyZWF0ZSBybWRpciBtb3VudG9uICkpKQogICAgKGFsbG93IHByb2Nlc3MgY29udGFpbmVyX2xvZ190ICggZmlsZSAoIHNldGF0dHIgZ2V0YXR0ciByZWFkIHdyaXRlIGFwcGVuZCBpb2N0bCBsb2NrIG1hcCBvcGVuIGNyZWF0ZSB1bmxpbmsgcmVuYW1lICkpKQogICAgKGFsbG93IHByb2Nlc3MgY29udGFpbmVyX2xvZ190ICggc29ja19maWxlICggZ2V0YXR0ciByZWFkIHdyaXRlIGFwcGVuZCBvcGVuICkpKQogICAgKGFsbG93IHByb2Nlc3MgY29udGFpbmVyX3Zhcl9saWJfdCAoIGRpciAoIG9wZW4gcmVhZCBzZXRhdHRyIGdldGF0dHIgbG9jayBzZWFyY2ggaW9jdGwgYWRkX25hbWUgcmVtb3ZlX25hbWUgd3JpdGUgY3JlYXRlIHJtZGlyIG1vdW50b24gKSkpCiAgICAoYWxsb3cgcHJvY2VzcyBjb250YWluZXJfdmFyX2xpYl90ICggZmlsZSAoIHNldGF0dHIgZ2V0YXR0ciByZWFkIHdyaXRlIGFwcGVuZCBpb2N0bCBsb2NrIG1hcCBvcGVuIGNyZWF0ZSB1bmxpbmsgbW91bnRvbiBleGVjdXRlIGV4ZWN1dGVfbm9fdHJhbnMgKSkpCiAgICAoYWxsb3cgcHJvY2VzcyBjb250YWluZXJfdmFyX2xpYl90ICggc29ja19maWxlICggZ2V0YXR0ciByZWFkIHdyaXRlIGFwcGVuZCBvcGVuICkpKQogICAgKGFsbG93IHByb2Nlc3MgY29udGFpbmVyX3Zhcl9saWJfdCAoIGxua19maWxlICggY3JlYXRlIHVubGluayByZWFkICkpKQogICAgKGFsbG93IHByb2Nlc3MgY29udGFpbmVyX3J1bnRpbWVfdCAoIHVuaXhfc3RyZWFtX3NvY2tldCAoIGNvbm5lY3R0byApKSkKICAgIChhbGxvdyBwcm9jZXNzIGNvbnRhaW5lcl92YXJfcnVuX3QgKCBmaWxlICggZ2V0YXR0ciByZWFkIG9wZW4gY3JlYXRlIHdyaXRlIHVubGluayBtb3VudG9uICkpKQogICAgKGFsbG93IHByb2Nlc3MgY29udGFpbmVyX3Zhcl9ydW5fdCAoIGRpciAoIHdyaXRlIGFkZF9uYW1lIGNyZWF0ZSBzZXRhdHRyIHJlbW92ZV9uYW1lIHJlYWQgcm1kaXIgdW5saW5rIG1vdW50b24gKSkpCiAgICAoYWxsb3cgcHJvY2VzcyBjb250YWluZXJfdmFyX3J1bl90ICggZmlmb19maWxlICggcmVhZCBvcGVuIHdyaXRlIGNyZWF0ZSBzZXRhdHRyIHVubGluayApKSkKICAgIChhbGxvdyBwcm9jZXNzIGNvbnRhaW5lcl90ICggZGlyICggc2VhcmNoIGdldGF0dHIgcmVhZCBvcGVuICkpKQogICAgKGFsbG93IHByb2Nlc3MgY29udGFpbmVyX3QgKCBmaWxlICggcmVhZCBvcGVuIGdldGF0dHIgKSkpCiAgICAoYWxsb3cgcHJvY2VzcyBjb250YWluZXJfdCAoIGxua19maWxlICggZ2V0YXR0ciByZWFkIG9wZW4gKSkpCiAgICAoYWxsb3cgcHJvY2VzcyBOZXR3b3JrTWFuYWdlcl90ICggZmlsZSAoIGdldGF0dHIgcmVhZCBvcGVuICkpKQogICAgKGFsbG93IHByb2Nlc3MgY2dyb3VwX3QgKCBmaWxlICggd3JpdGUgcmVhZCBjcmVhdGUgKSkpCiAgICAoYWxsb3cgcHJvY2VzcyBjZ3JvdXBfdCAoIGRpciAoIHdyaXRlIGFkZF9uYW1lIHJlbW92ZV9uYW1lIHJtZGlyICkpKQogICAgKGFsbG93IHByb2Nlc3MgcHJvY190ICggZmlsZXN5c3RlbSAoIG1vdW50ICkpKQogICAgKGFsbG93IHByb2Nlc3MgdG1wZnNfdCAoIGZpbGVzeXN0ZW0gKCBtb3VudCApKSkKICAgIChhbGxvdyBwcm9jZXNzIGRldnB0c190ICggZmlsZXN5c3RlbSAoIG1vdW50ICkpKQogICAgKGFsbG93IHByb2Nlc3Mgc3lzZnNfdCAoIGZpbGVzeXN0ZW0gKCBtb3VudCApKSkKICAgIChhbGxvdyBwcm9jZXNzIHNwY190ICggZGlyICggc2VhcmNoIGdldGF0dHIgb3BlbiByZWFkICkpKQogICAgKGFsbG93IHByb2Nlc3Mgc3BjX3QgKCBmaWxlICggcmVhZCBvcGVuIGdldGF0dHIgKSkpCiAgICAoYWxsb3cgcHJvY2VzcyBzcGNfdCAoIGxua19maWxlICggZ2V0YXR0ciByZWFkIG9wZW4gKSkpCiAgICAoYWxsb3cgcHJvY2VzcyBpbml0X3QgKCBkaXIgKHNlYXJjaCBnZXRhdHRyIG9wZW4gcmVhZCApKSkKICAgIChhbGxvdyBwcm9jZXNzIGluaXRfdCAoIGZpbGUgKCByZWFkIG9wZW4gKSkpCiAgICAoYWxsb3cgcHJvY2VzcyBpbml0X3QgKCBsbmtfZmlsZSAoIHJlYWQgKSkpCikK
          verification: {}
        mode: 0755
    systemd:
      units:
        - contents: |
            [Unit]
            Requires=systemd-udevd.target
            After=NetworkManager.service
            Before=sshd.service
            DefaultDependencies=no
            [Service]
            Type=oneshot
            ExecStart=/usr/sbin/semodule -i /etc/selinux/gremlin-ocp4.cil
            [Install]
            WantedBy=multi-user.target
          name: one-shot-gremlin-ocp4.service
          enabled: true
